config/routes.rb
Rails.application.routes.draw do
  get      '/login',   to:  'sessions#new'
  post     '/login',   to:  'sessions#create'
  delete   '/logout',  to:  'sessions#destroy'
  resources :users, only: [:new, :create, :show] 
  resources :events, only: [:new, :create, :show, :index]

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :date, presence: true
  has_many :guests
  belongs_to :creator, class_name: 'User'
  has_many :attendees, through: :guests, source: :user

  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :username, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :guests
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :attended_events, through: :guests, source: :event

  def upcoming_events
    attended_events.where('date > date(\'now\')')
  end

  def previous_events
    attended_events.where('date < date(\'now\')')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include SessionsHelper

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(events_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def index
    @events = Event.all
    @past_events = Event.past
    @upcoming = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
    @creator = @event.creator
  end

  private

  def events_params
    params.require(:event).permit(:title, :description, :location, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user
      log_in @user
      redirect_to @user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def users_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_new_event.html.erb
<%= form_for(@event) do |f| %>
  <div>
    <div><%= f.label :title %></div>
    <div><%= f.text_field :title %></div>
  </div>
  <div>
    <%= f.label :description, class:'label' %>
    <%= f.text_field :description, class:"field" %>
  </div>
  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div>
    <%=f.label:date%>
    <%=f.date_field :date %>
  </div>
  <div>
    <%= submit_tag 'Create event' %>
  </div>
  <% end %>

app/views/events/index.html.erb
<h3>All Events</h3>
<p>click on each event to see the creator<p>
<br>
<% @events.each do |event| %>
    <p><%= link_to event.title, event_path(event), class:"events" %></p>
<% end %>

<h3>Past Events</h3>
<% if !@past_events.empty? %>
  <% @past_events.each do |event| %>
    <div class="event-box">
    <p><span>Tittle:</span> <%= event.title %></p>
    <p><span>Description:</span> <%= event.description %></p>
    <p><span>Location: </span><%= event.location %></p>
    <p><span>Date: </span><%= event.date %></p>
    </div>
  <% end %>
<% else %>
  <p>There is no any past events</p>
<% end %>

<h3>Upcoming Events</h3>
<% if !@upcoming.empty? %>
  <% @upcoming.each do |event| %>
    <div class="event-box">
    <p><span>Tittle:</span> <%= event.title %></p>
    <p><span>Description:</span> <%= event.description %></p>
    <p><span>Location: </span><%= event.location %></p>
    <p><span>Date: </span><%= event.date %></p>
    </div>
  <% end %>
<% else %>
  <p>There is no any upcoming events</p>
<% end %>

app/views/events/new.html.erb
<div class='form-box'>
  <h1>Create Event</h1>
  <%= render 'new_event' %>
</div>

app/views/events/show.html.erb
<div class='event-show'>
<h3>This event was created by: <span><%= @creator.username %></span></h3>
<h3>List of Attendees</h3>
<% if !@event.attendees.empty? %>
  <% @event.attendees.each do |attendee| %>
    <p><%= attendee.username %><p>
  <% end %>
<% else %>
  <p>No any attendees recorded for this event<p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='nav-bar'>
    <div class='nav-content'>
     <div><%= link_to "Private Event","#", class:"nav-link" %></div>
     <div>
       <% if logged_in? %>
       <%= link_to "Create event", new_event_path, class:"nav-link" %>
       <%= link_to "Logout", logout_path, method: :delete, class:"nav-link" %>
       <% else %>
       <%= link_to "Sign up", new_user_path, class:"nav-link" %>
       <%= link_to "Login", login_path, class:"nav-link" %>
       <% end %>
     </div>
    </div>
    </div>
    <div class='main-container'>
    <%= yield %>
    <div>
  </body>
</html>

app/views/users/_signup_form.html.erb
<%= form_for(@user) do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%=f.label:password_confirmation,"Confirmation"%>
    <%=f.password_field:password_confirmation%>
  </div>
  <div>
    <%= submit_tag "Create account" %>
  </div>
  <p>Already have an account?<%=link_to"Login!", login_path%></p>
<% end %>

app/views/users/_users_event.html.erb
<h3>Events created by <%= @user.username %></h3>
<% if !@user.created_events.empty? %>
  <% @user.created_events.each do |event| %>
    <div class="event-box">
      <p><span>Tittle:</span> <%= event.title %></p>
      <p><span>Description:</span> <%= event.description %></p>
      <p><span>Location: </span><%= event.location %></p>
      <p><span>Date: </span><%= event.date %></p>
    </div>
  <% end %>
<% else %>
 <p>No events created by <%= @user.username %></p>
<% end %>
<h3>Events attended by <%= @user.username %></h3>
<% if !@user.attended_events.empty? %>
  <% @user.attended_events.each do |event| %>
    <div class="event-box">
      <p><span>Tittle :</span><%= event.title %></p>
      <p><span>Description:</span> <%= event.description %></p>
      <p><span>Location: </span><%= event.location %></p>
      <p><span>Date: </span><%= event.date %></p>
    </div>
  <% end %>
<% else %>
 <p><%= @user.username %> is not attending any events</p>
<% end %>
<h3><%= @user.username %>'s Upcoming Events</h3>
<% if !@user.upcoming_events.empty? %>
<% @user.upcoming_events.each do |event| %>
  <div class="event-box">
    <p><span>Tittle: </span><%= event.title %></p>
    <p><span>Description:</span> <%= event.description %></p>
    <p><span>Location: </span><%= event.location %></p>
    <p><span>Date: </span><%= event.date %></p>
  </div>
<% end %>
<% else %>
<p><%= @user.username %> does not have any upcoming events</p>
<% end %>
<h3><%= @user.username %>'s Previous Events</h3>
<% if !@user.previous_events.empty? %>
<% @user.previous_events.each do |event| %>
  <div class="event-box">
    <p><span>Tittle: </span><%= event.title %></p>
    <p><span>Description:</span> <%= event.description %></p>
    <p><span>Location: </span><%= event.location %></p>
    <p><span>Date: </span><%= event.date %></p>
  </div>
<% end %>
<% else %>
<p><%= @user.username %> does not have any previous events</p>
<% end %>

app/views/users/new.html.erb
<div class="form-box" >
<h1>Sign up</h1>
<%= render 'signup_form' %>
</div>

app/views/users/show.html.erb
<% if (logged_in? && @user.id==current_user.id) %>
  <%= render 'users_event' %>
<% else %>
  <br>
<%= link_to "Login First", login_path%>
<% end %>